name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install-command: "echo 'deps already installed'"
          runTests: true 